version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./assets:/usr/share/nginx/html/assets
