[build]
  command = ""  # No build command needed since you're using a Dockerfile
  publish = "usr/share/nginx/html"  # Publish the files from this directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'"

[netlify]
  auth = "ro2w5lhv55baslhketfh4awyyw2sdsknj66ncqwk6ado5wwn4dpa"
  site = "fe2786f3-5089-4909-ada8-b0e2ebf86a9d"
